# Generated by Django 4.2.6 on 2023-10-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glyph",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("pub_date", models.DateTimeField()),
                ("parola", models.CharField(max_length=200)),
                ("categoria_semantica", models.CharField(max_length=200)),
                ("funzione_grammaticale", models.CharField(max_length=200)),
                ("figura_retorica", models.CharField(max_length=200)),
                ("glyphFile", models.FileField(upload_to="glyphs/")),
            ],
        ),
    ]
