# Generated by Django 4.2.6 on 2023-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glyph",
            name="funzione_grammaticale",
            field=models.CharField(
                choices=[
                    ("Sostantivo", "Sostantivo"),
                    ("Verbo", "Verbo"),
                    ("Avverbio", "Avverbio"),
                    ("Parola grammaticale", "Parola grammaticale"),
                    ("Aggettivo", "Aggettivo"),
                ],
                max_length=200,
            ),
        ),
    ]
