# Generated by Django 4.2.6 on 2023-11-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0002_alter_glyph_funzione_grammaticale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glyph",
            name="categoria_semantica",
            field=models.CharField(
                choices=[
                    ("Abbigliamento", "Abbigliamento"),
                    ("Altro", "Altro"),
                    ("Animali", "Animali"),
                    ("Azioni", "Azioni"),
                    ("Bevande", "Bevande"),
                    ("Condizioni metereologiche", "Condizioni metereologiche"),
                    ("Mestieri", "Mestieri"),
                    ("Mezzi di trasporto", "Mezzi di trasporto"),
                    ("Oggetti", "Oggetti"),
                    ("Saluti", "Saluti"),
                    ("Sostanze", "Sostanze"),
                    ("Sport", "Sport"),
                ],
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="SelectedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foreignGlyph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coreApp.glyph"
                    ),
                ),
            ],
        ),
    ]
