# Generated by Django 4.2.6 on 2023-11-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("coreApp", "0003_alter_glyph_categoria_semantica_selectedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedimage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sessions.session",
            ),
        ),
    ]
