# Generated by Django 4.2.6 on 2023-11-09 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("coreApp", "0004_selectedimage_session"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="selectedimage",
            unique_together={("foreignGlyph", "session")},
        ),
    ]
