# Generated by Django 4.2.6 on 2023-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0005_alter_selectedimage_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="glyph",
            name="id_variante",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="glyph",
            name="parola_ENG",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="glyph",
            name="variante",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="glyph",
            name="figura_retorica",
            field=models.CharField(
                choices=[
                    ("Analogia", "Analogia"),
                    ("Letterale", "Letterale"),
                    ("Metonimina", "Metonimina"),
                    ("Sineddoche", "Sineddoche"),
                    ("Simbolico", "Simbolico"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="glyph",
            name="id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
