# Generated by Django 4.2.6 on 2023-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0006_glyph_id_variante_glyph_parola_eng_glyph_variante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="glyph",
            name="approvato",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="glyph",
            name="presenza_umana",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="glyph",
            name="variante",
            field=models.BooleanField(default=False, verbose_name="is alternative"),
        ),
    ]
