# Generated by Django 4.2.6 on 2023-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0007_glyph_approvato_glyph_presenza_umana_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glyph",
            name="approvato",
            field=models.BooleanField(default=True),
        ),
    ]
