# Generated by Django 4.2.6 on 2023-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0008_alter_glyph_approvato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glyph",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
