# Generated by Django 4.2.6 on 2023-11-28 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0009_alter_glyph_pub_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glyph",
            old_name="pub_date",
            new_name="created_at",
        ),
    ]
