# Generated by Django 4.2.6 on 2023-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreApp", "0010_rename_pub_date_glyph_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="glyph",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
